---
sidebar: sidebar 
permalink: learn/data-protection.html 
keywords: backup, back up, backup apps, back up apps, snapshots, snapshot an app, take a snapshot, take a backup, view backups, view snapshots, set policy, set schedule, schedule backups, schedule snapshots, protect data 
summary: 了解Astra控制服务中可用的数据保护类型、以及如何以最佳方式使用它们来保护您的应用程序。 
---
= 数据保护
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


[role="lead"]
了解Astra控制服务中可用的数据保护类型、以及如何以最佳方式使用它们来保护您的应用程序。



== 快照，备份和保护策略

快照和备份均可保护以下类型的数据：

* 应用程序本身
* 与应用程序关联的任何永久性数据卷
* 属于应用程序的任何资源项目


_snapshot_ 是应用程序的时间点副本，它与应用程序存储在同一个已配置卷上。通常速度较快。您可以使用本地快照将应用程序还原到较早的时间点。快照对于快速克隆很有用；快照包括应用程序的所有 Kubernetes 对象，包括配置文件。快照对于克隆或还原同一集群中的应用程序非常有用。

_backup_基于快照。它存储在外部对象存储中、因此、与本地快照相比、创建速度可能会较慢。您可以将应用程序备份还原到同一集群，也可以通过将应用程序备份还原到其他集群来迁移应用程序。您还可以选择较长的备份保留期限。由于备份存储在外部对象存储中，因此在发生服务器故障或数据丢失时，备份通常比快照提供更好的保护。

保护策略 _ 是一种通过根据您为应用程序定义的计划自动创建快照和 / 或备份来保护应用程序的方法。此外、您还可以通过保护策略选择要在计划中保留多少个快照和备份、并设置不同的计划粒度级别。使用保护策略自动执行备份和快照是确保每个应用程序根据组织的需求和服务级别协议(Service Level Agreement、SLA)要求进行保护的最佳方式。


CAUTION: _You can't be Fully protected until you have a recent backup_ 。这一点非常重要，因为备份存储在对象存储中，而不是永久性卷。如果发生故障或意外事件会擦除集群及其关联的永久性存储，则需要备份才能恢复。快照无法让您恢复。


NOTE: 如果您执行快照或备份、但操作失败并显示错误"The resource was n't created because of an internal server问题描述 "、请检查以确保您正在使用的存储后端安装了正确的驱动程序。某些存储后端需要容器存储接口(CSI)驱动程序、而其他存储后端则需要外部快照控制器。



=== 不可配置的备份

Astra Control Service支持使用以下平台和存储分段类型创建不可配置的备份：

* Amazon Web Services使用配置了S3对象锁定的Amazon S3存储分段
* Microsoft Azure使用已配置保留策略的Azure存储分段
* 使用配置了保留策略的Google Cloud Storage存储分段的Google Kub并 配置了保留策略
* 使用配置了S3对象锁定的S3存储分段的NetApp StorageGRID


使用不可配置备份时、请注意以下事项：

* 如果备份到不受支持的平台中的一次写入多次读取(WORM)存储分段或备份到不受支持的存储分段类型、则可能会出现不可预测的结果、例如、即使已过保留时间、备份删除也会失败。
* Astra Control不支持数据生命周期管理策略、也不支持手动删除用于不可变备份的存储分段上的对象。确保存储后端未配置为管理Astra Control快照或备份数据的生命周期。




== 克隆

_cloner_是应用程序、其配置及其永久性数据卷的精确副本。您可以在同一个 Kubernetes 集群或另一个集群上手动创建克隆。如果需要将应用程序和存储从一个 Kubernetes 集群移动到另一个 Kubernetes 集群，则克隆应用程序非常有用。
