---
sidebar: sidebar 
permalink: solutions/mysql-deploy-from-helm-chart.html 
keywords: helm, mysql, helm chart, deploy mysql, astra, astra control, kubernetes 
summary: 从标准稳定图表中了解如何部署 MySQL 。在 Kubernetes 集群上部署 MySQL 后，您可以使用 Astra Control 管理此应用程序。 
---
= 从 Helm 图表部署 MySQL
:hardbreaks:
:icons: font
:imagesdir: ../media/


了解如何从部署 MySQL https://github.com/helm/charts/tree/master/stable/mysql["标准稳定图表"^]。在 Kubernetes 集群上部署 MySQL 后，您可以使用 Astra Control 管理此应用程序。

MySQL 是经过验证的适用于 Astra Control 的应用程序。 link:../learn/validated-vs-standard.html["了解经过验证的应用程序与标准应用程序之间的区别"]。

这些说明同时适用于 Astra 控制服务和 Astra 控制中心。



== 要求

* 已添加到 Astra Control 的集群。
+

NOTE: 对于 Astra 控制中心，您可以先将集群添加到 Astra 控制中心，或者先添加应用程序。

* 更新了安装在本地计算机上的 Helm （版本 3.2+ ）和 Kubectl 的版本，并为集群提供了正确的 kubeconfig




== 安装 MySQL

有关此过程的两个重要注意事项：

* 您必须在将集群添加到 Astra Control Service 后部署应用程序，而不是在之前部署。在将集群添加到 Astra 控制中心之前或之后， Astra 控制中心将接受应用程序。
* 建议您将 Helm 图表部署在非默认命名空间中。


.步骤
. 添加 BitNami 图表 repo ：
+
[listing]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----
. 使用以下命令部署 MySQL ：
+
[listing]
----
helm install <name> bitnami/mysql --namespace <namespace> --create-namespace -–set persistence.storageClass=<storage_class>
----
+

NOTE: 如果卷大小发生更改，请使用 Kibibyte （ KI ）， mebibyte （ Mi ）或 Gibibyte （ Gi ）单位。

+
只有在以下情况下才需要定义存储类：

+
** 您正在使用 Astra 控制服务，并且不想使用默认存储类。
** 您正在使用 Astra 控制中心，但尚未将集群导入到 Astra 控制中心。或者，您已导入集群，但不想使用默认存储类。




此操作将执行以下操作：

* 创建命名空间。
* 在命名空间上部署 MySQL 。


Pod 联机后，您可以使用 Astra Control 管理应用程序。使用 Astra Control ，您可以在命名空间级别或使用 Helm 标签管理应用程序及其名称。
