---
sidebar: sidebar 
permalink: use/clone-apps.html 
keywords: clone app, clone storage, clone persistent storage, clone data, move workload, clone data, migrate data, data migration, move storage, move application, move data 
summary: 克隆现有应用程序以在同一个 Kubernetes 集群或另一个集群上创建重复的应用程序。如果您需要将应用程序和存储从一个 Kubernetes 集群移动到另一个集群，则克隆可以助您一臂之力。例如，您可能希望通过 CI CD 管道和 Kubernetes 命名空间移动工作负载。 
---
= 克隆和迁移应用程序
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
您可以克隆现有应用程序、以便在同一个Kubernetes集群或另一个集群上创建重复的应用程序。当 Astra Control 克隆应用程序时，它会为您的应用程序配置和永久性存储创建一个克隆。

如果您需要将应用程序和存储从一个 Kubernetes 集群移动到另一个集群，则克隆可以助您一臂之力。例如，您可能希望通过 CI/CD 管道以及在 Kubernetes 命名空间之间移动工作负载。

.您需要的内容
* 要将应用程序克隆到其他集群、您需要确保已为包含源集群的云实例分配默认分段。如果源云实例未设置默认分段、则跨集群克隆操作将失败。
* 在克隆操作期间、需要IngressClass资源或webhooks才能正常运行的应用程序不能在目标集群上定义这些资源。


.克隆限制
* *显式存储类*：如果部署的应用程序已明确设置存储类、并且需要克隆此应用程序、则目标集群必须具有最初指定的存储类。将具有显式设置的存储类的应用程序克隆到没有相同存储类的集群将失败。
* *克隆和用户约束*：任何按命名空间名称/ID或命名空间标签限制命名空间的成员用户都可以将应用程序克隆或还原到同一集群上的新命名空间或其组织帐户中的任何其他集群。但是，同一用户无法访问新命名空间中的克隆或还原应用程序。通过克隆或还原操作创建新命名空间后，帐户管理员 / 所有者可以编辑成员用户帐户并更新受影响用户的角色约束，以授予对新命名空间的访问权限。
* *克隆使用默认分段*：
+
** 在应用程序备份或应用程序还原期间、您可以指定要使用的存储分段。在跨集群克隆时、需要指定默认分段、但在同一集群内克隆时、指定分段是可选的。
** 在集群间克隆时、包含克隆操作的源集群的云实例必须设置默认分段。
** 没有选项可用于更改克隆的分段。如果要控制使用哪个存储分段，您可以选择 link:../use/manage-buckets.html#edit-a-bucket["更改存储分段默认值"] 或者执行 link:../use/protect-apps.html#create-a-backup["backup"] 后跟 A link:../use/restore-apps.html["还原"] 请单独使用。


* *使用Jenkins CI*：如果克隆操作员部署的Jenkins CI实例、则需要手动还原持久数据。这是应用程序部署模式的一个限制。


.步骤
. 选择 * 应用程序 * 。
. 执行以下操作之一：
+
** 在 * 操作 * 列中选择所需应用程序的选项菜单。
** 选择所需应用程序的名称，然后选择页面右上角的状态下拉列表。


. 选择 * 克隆 * 。
. 指定克隆的详细信息：
+
** 输入名称。
** 选择克隆的目标集群。
** 输入克隆的目标命名空间。与应用程序关联的每个源命名空间都会映射到一个目标命名空间。
+

NOTE: 在克隆操作中、Astra Control会创建新的目标命名空间。指定的目标命名空间不能已存在于目标集群上。

** 选择 * 下一步 * 。
** 选择是要从现有快照还是备份创建克隆。如果不选择此选项，则 Astra Control 将根据应用程序的当前状态创建克隆。
+
*** 如果选择从现有快照或备份克隆、请选择要使用的快照或备份。




. 选择 * 下一步 * 。
. 查看有关克隆的信息、然后选择*克隆*。


.结果
Astra Control会根据您提供的信息克隆应用程序。当新应用程序克隆处于中时、克隆操作成功 `Healthy` 状态。

通过克隆或还原操作创建新命名空间后，帐户管理员 / 所有者可以编辑成员用户帐户并更新受影响用户的角色约束，以授予对新命名空间的访问权限。
