---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: 随时在您的帐户中添加和删除云提供商凭据。Astra Control 使用这些凭据代表您配置资源。 
---
= 添加和删除凭据
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


随时在您的帐户中添加和删除云提供商凭据。Astra Control 使用这些凭据来发现 Kubernetes 集群，集群上的应用程序，并代表您配置资源。

请注意， Astra Control 中的所有用户都共享相同的凭据集。



== 添加凭据

向 Astra Control 添加凭据的最常见方法是管理集群，但您也可以从帐户页面添加凭据。然后，在管理其他 Kubernetes 集群时，您可以选择这些凭据。

.您需要什么？ #8217 ；将需要什么
* 对于 GKE- ，您应该拥有具有所需权限的服务帐户的服务帐户密钥文件。 link:../get-started/set-up-google-cloud.html["了解如何设置服务帐户"]。
* 对于 AKS ，您应具有包含创建服务主体时 Azure 命令行界面输出的 JSON 文件。 link:../get-started/set-up-microsoft-azure-with-anf.html["了解如何设置服务主体"]。
+
如果未将 Azure 订阅 ID 添加到 JSON 文件中，您也需要此 ID 。



.步骤
. 选择 * 帐户 > 凭据 * 。
. 选择 * 添加凭据 * 。
. 选择 * Microsoft Azure* 或 * Google Cloud Platform* 。
. 在 Astra Control 中输入凭据名称，以便将其与其他凭据区分开。
. 提供所需的凭据。
+
.. * Microsoft Azure* ：通过上传 JSON 文件或从剪贴板粘贴 JSON 文件的内容，为 Astra Control 提供有关 Azure 服务主体的详细信息。
+
JSON 文件应包含创建服务主体时 Azure 命令行界面的输出。它还可以包括您的订阅 ID ，以便自动添加到 Astra Control 。否则，您需要在提供 JSON 后手动输入 ID 。

.. * Google Cloud Platform* ：通过上传文件或粘贴剪贴板中的内容来提供 Google Cloud 服务帐户密钥文件。


. 选择 * 添加凭据 * 。


现在，您可以在向 Astra Control 添加集群时选择这些凭据。



== 删除凭据

随时从帐户中删除凭据。您只能在之后删除凭据 link:unmanage.html["取消管理所有集群"]、除非您正在轮换凭据(请参见 <<Rotate credentials>>）。


NOTE: 添加到 Astra Control 的第一组凭据始终处于使用状态，因为 Astra Control 使用这些凭据向备份存储分段进行身份验证。最好不要删除这些凭据。

.步骤
. 选择 * 帐户 > 凭据 * 。
. 在 * 状态 * 列中选择要删除的凭据的下拉列表。
. 选择 * 删除 * 。
. 键入凭据名称以确认删除，然后选择 * 是，删除凭据 * 。


Astra Control 会从帐户中删除凭据。



== 轮换凭据

您可以轮换帐户中的凭据。如果要轮换凭据、请在维护窗口中没有正在进行的备份(计划备份或按需备份)时轮换凭据。

.步骤
. 按照中的步骤删除现有凭据 <<Remove credentials>>。
. 按照中的步骤添加新凭据 <<Add credentials>>。
. 更新所有分段以使用新凭据：
+
.. 在 * 管理存储 * 下，选择 * 分段 * 。
.. 在 * 操作 * 列中选择要编辑的存储分段的下拉列表。
.. 选择 * 编辑 * 。
.. 在*选择凭据*部分中、选择添加到Astra Control的新凭据。
.. 选择 * 更新 * 。
.. 对系统上的任何剩余存储分段重复步骤* b*到* e*。




Astra Control开始使用新的云提供商凭据。
