---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: 通过添加其他存储分段以及更改云提供商中集群的默认存储分段，管理 Astra 用于备份和克隆的存储分段。 
---
= 管理存储分段
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
您可以管理Astra用于备份和克隆的存储分段。您可以在云实例中添加其他分段、删除现有分段以及更改Kubernetes集群的默认分段。

只有所有者和管理员才能管理存储分段。



== Astra Control 如何使用存储分段

当您开始管理云实例的第一个Kubernetes集群时、Astra Control Service会为此创建初始存储分段 link:manage-cloud-instances.html["云实例"^]。

您可以手动将存储分段指定为云实例的默认存储分段。如果您这样做、则Astra控制服务会默认对您在该云实例中的任何受管集群上创建的备份和克隆使用此存储分段(您可以选择其他存储分段进行备份)。如果您将应用程序从云实例中的任何受管集群实时克隆到另一个集群、则Astra Control Service会使用源云实例的默认分段来执行克隆操作。

您可以为多个云实例设置与默认分段相同的分段。

您可以在创建保护策略或启动临时备份时从任何存储分段中进行选择。


TIP: 在启动备份或克隆之前， Astra 控制服务会检查目标存储分段是否可访问。



== 查看现有存储分段

查看可供Astra控制服务使用的分段列表、以确定其状态并确定云实例的默认分段(如果已定义)。

存储分段可以具有以下任一状态：

待定:: 添加存储分段后、它将以待定状态启动、而Astra Control会发现它。
可用:: 此存储分段可供 Astra Control 使用。
已删除:: 存储分段目前无法正常运行。将鼠标悬停在状态图标上可确定问题所在。
+
--
如果某个存储分段处于 "Removed" 状态，您仍可以将其设置为默认存储分段并将其分配给保护计划。但是，如果数据保护操作开始时存储分段未处于可用状态，则该操作将失败。

--


.步骤
. 转至*分段器*。
+
此时将显示可供Astra控制服务使用的分段列表。





== 添加一个额外的存储分段

您可以随时添加其他分段。这样、您可以在创建保护策略或启动临时备份时在存储分段之间进行选择、并可以更改云实例使用的默认存储分段。

您可以添加以下类型的存储分段：

* Amazon Web Services
* 通用 S3
* Google 云平台
* Microsoft Azure
* NetApp ONTAP S3
* NetApp StorageGRID S3


.您需要的内容
* 现有存储分段的名称。
* 用于为Astra Control Service提供管理存储分段所需权限的存储分段凭据。


ifdef::azure[]

* 如果存储分段位于Microsoft Azure中：
+
** 此存储分段必须属于名为_Astra-backup-rg_的资源组。
** 如果Azure存储帐户实例性能设置为"Premium"、则"Premium account type"设置必须设置为"Block blobs"。




endif::azure[]

.步骤
. 转至*分段器*。
. 选择 * 添加 * ，然后按照提示添加存储分段。
+
** * 类型 * ：选择您的云提供商。
** * 现有存储分段名称 * ：输入存储分段的名称。
** * 问题描述 * ：也可以输入存储分段的问题描述。




ifdef::azure[]

* *存储帐户*(仅限Azure)：输入Azure存储帐户的名称。此存储分段必须属于名为_Astra-backup-rg_的资源组。


endif::azure[]

ifdef::aws[]

* * S3服务器名称或IP地址*(仅限AWS和S3存储分段类型)：输入与您所在地区对应的S3端点的完全限定域名、而不输入 `https://`。请参见 https://docs.aws.amazon.com/general/latest/gr/s3.html["Amazon文档"^] 有关详细信息 ...


endif::aws[]

* *选择凭据*：输入为Astra控制服务提供管理存储分段所需权限的凭据。您需要提供的信息因存储分段类型而异。
+
.. 选择 * 添加 * 以添加存储分段。




.结果
Astra Control Service添加了存储分段。现在、您可以在创建保护策略或执行临时备份时选择此存储分段。您也可以将此分段设置为云实例的默认分段。



== 更改默认分段

您可以更改云实例的默认存储分段。默认情况下、Astra Control Service会将此存储分段用于备份和克隆。每个云实例都有自己的默认存储分段。


NOTE: Astra Control不会自动为任何云实例分配默认分段。在两个集群之间执行应用程序克隆操作之前、您需要手动为云实例设置默认分段。

.步骤
. 转至*云实例*。
. 在*操作*列中选择要编辑的云实例的配置菜单。
. 选择 * 编辑 * 。
. 在存储分段列表中、选择要用作此云实例的默认存储分段的存储分段。
. 选择 * 更新 * 。




== 删除存储分段

您可以删除不再使用或运行状况不佳的存储分段。您可能需要执行此操作以使对象存储配置简单且最新。

您不能删除默认存储分段。如果要删除此存储分段，请先选择另一个存储分段作为默认存储。

.您需要的内容
* 开始之前，应检查以确保此存储分段没有正在运行或已完成的备份。
* 您应进行检查，以确保存储分段未用于任何计划的备份。


如果存在，您将无法继续。

.步骤
. 转至*分段器*。
. 从 * 操作 * 菜单中，选择 * 删除 * 。
+

NOTE: Astra Control 可首先确保没有使用存储分段进行备份的计划策略，并且要删除的存储分段中没有活动备份。

. 键入 "remove" 确认此操作。
. 选择 * 是，删除存储分段 * 。




== 了解更多信息

* https://docs.netapp.com/us-en/astra-automation/index.html["使用 Astra Control API"^]

