---
sidebar: sidebar 
permalink: use/manage-roles.html 
keywords: users, roles, user roles, namespace, namespaces, account, accounts, permissions, restriction, restrict, constraint, constraints 
summary: 了解如何通过向角色添加限制来管理用户角色。 
---
= 管理角色
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


您可以通过添加命名空间限制并将用户角色限制为这些限制来管理角色。这样，您就可以控制对组织内资源的访问。您可以使用 Astra Control UI 或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 以管理角色。



== 向角色添加命名空间限制

管理员或所有者用户可以添加命名空间约束。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 用户 * 选项卡。
. 在 * 操作 * 列中，为具有成员或查看器角色的用户选择菜单按钮。
. 选择 * 编辑角色 * 。
. 启用 * 将角色限制为约束条件 * 复选框。
+
此复选框仅适用于 " 成员 " 或 " 查看器 " 角色。您可以从 * 角色 * 下拉列表中选择其他角色。

. 选择 * 添加约束 * 。
+
您可以按命名空间或命名空间标签查看可用约束的列表。

. 在 * 约束类型 * 下拉列表中，根据命名空间的配置方式选择 * Kubernetes 命名空间 * 或 * Kubernetes 命名空间标签 * 。
. 从列表中选择一个或多个命名空间或标签，以构成一个限制，将角色限制为这些命名空间。
. 选择 * 确认 * 。
+
"* 编辑角色 * " 页面将显示您为此角色选择的约束列表。

. 选择 * 确认 * 。
+
在 * 帐户 * 页面上，您可以在 * 角色 * 列中查看任何成员或查看器角色的限制。




NOTE: 如果为某个角色启用了限制并选择了 * 确认 * 而未添加任何限制，则该角色将被视为具有完全限制（该角色将被拒绝访问分配给命名空间的任何资源）。



== 从角色中删除命名空间限制

管理员或所有者用户可以从角色中删除命名空间限制。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 用户 * 选项卡。
. 在 * 操作 * 列中，为具有成员或查看器角色且具有活动约束的用户选择菜单按钮。
. 选择 * 编辑角色 * 。
+
"* 编辑角色 " 对话框显示角色的活动约束。

. 选择需要删除的约束右侧的 * X * 。
. 选择 * 确认 * 。




== 有关详细信息 ...

* link:../learn/user-roles-namespaces.html["用户角色和命名空间"]

