---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra Control 可以从快照或备份还原应用程序配置和永久性存储。永久性存储备份会从对象存储传输，因此从现有备份还原的速度最快。 
---
= 还原应用程序
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control 可以从快照或备份还原应用程序。将应用程序还原到同一集群时，从现有快照进行还原的速度会更快。您可以使用 Astra Control UI 或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 还原应用程序。


NOTE: 对使用NetApp ONTAP 存储的应用程序执行原位还原时、还原的应用程序使用的空间可能会增加一倍。执行原位还原后、从还原的应用程序中删除所有不需要的快照以释放存储空间。


NOTE: 如果将命名空间筛选器添加到在还原或克隆操作之后运行的执行挂钩、并且还原或克隆源和目标位于不同的命名空间中、则命名空间筛选器仅会应用于目标命名空间。

.关于此任务
* *首先保护应用程序*：强烈建议在还原应用程序之前为其创建快照或备份。这样、您可以在还原失败时从快照或备份克隆。
* *检查目标存储类*：如果要还原到其他集群、请确保目标集群的存储类与源集群上的存储类使用相同的永久性卷访问模式(例如ReadWriteMany)。如果目标永久性卷访问模式不同，还原操作将失败。


.步骤
. 选择 * 应用程序 * ，然后选择应用程序的名称。
. 选择 * 数据保护 * 。
. 如果要从快照还原，请保持选中 * 快照 * 。否则，请选择 * 备份 * 以从备份中还原。
. 从要还原的快照或备份的 * 操作 * 列的选项菜单中，选择 * 还原应用程序 * 。
. 选择还原类型：
+
** *还原到原始命名空间*：使用此操作步骤 将应用程序原位还原到原始集群。
+
[CAUTION]
====
在与其他应用程序共享资源的应用程序上执行原位还原操作可能会产生意外结果。对其中一个应用程序执行原位还原时、这些应用程序之间共享的任何资源都会被替换。

====
+
... 选择用于原位还原应用程序的快照、此操作会将应用程序还原到其自身的早期版本。
... 选择 * 下一步 * 。
+

NOTE: 如果还原到先前已删除的命名空间、则在还原过程中会创建一个同名的新命名空间。任何有权管理先前删除的命名空间中的应用程序的用户都需要手动还原对新重新创建的命名空间的权限。

... 查看有关还原操作的详细信息、键入"restore"、然后选择*还原*。


** *还原到新命名空间*：使用此操作步骤 将应用程序还原到另一个集群或使用与源不同的命名空间。
+
... 为要还原的应用程序选择目标集群。
... 为与应用程序关联的每个源命名空间输入目标命名空间。
+

NOTE: 作为此还原选项的一部分、Astra Control会创建新的目标命名空间。指定的目标命名空间不能已存在于目标集群上。

... 选择 * 下一步 * 。
... 选择用于还原应用程序的快照。
... 选择 * 下一步 * 。
... 查看有关还原操作的详细信息、然后选择*还原*。






.结果
Astra Control 会根据您提供的信息还原应用程序。如果您已原位还原应用程序、则现有永久性卷的内容将替换为已还原应用程序中的永久性卷的内容。


NOTE: 任何按命名空间名称/ID或命名空间标签限制命名空间的成员用户都可以将应用程序克隆或还原到同一集群上的新命名空间或其组织帐户中的任何其他集群。但是，同一用户无法访问新命名空间中的克隆或还原应用程序。通过克隆或还原操作创建新命名空间后，帐户管理员 / 所有者可以编辑成员用户帐户并更新受影响用户的角色约束，以授予对新命名空间的访问权限。
