---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore, migrate nas-economy 
summary: Astra Control 可以从快照或备份还原应用程序配置和永久性存储。永久性存储备份会从对象存储传输，因此从现有备份还原的速度最快。 
---
= 还原应用程序
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control 可以从快照或备份还原应用程序。将应用程序还原到同一集群时，从现有快照进行还原的速度会更快。您可以使用 Astra Control UI 或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 还原应用程序。


NOTE: 如果将命名空间筛选器添加到在还原或克隆操作之后运行的执行挂钩、并且还原或克隆源和目标位于不同的命名空间中、则命名空间筛选器仅会应用于目标命名空间。

.关于此任务
* *首先保护您的应用程序*：强烈建议您在恢复应用程序之前为其创建快照或备份。这样、您可以在还原失败时从快照或备份克隆。
* *检查目标卷*：如果要还原到其他集群、请确保此集群使用相同的永久性卷访问模式(例如ReadWriteMany)。如果目标永久性卷访问模式不同，还原操作将失败。
* *规划空间需求*：对使用NetApp ONTAP 存储的应用程序执行原位还原时、还原的应用程序使用的空间可能会增加一倍。执行原位还原后、从还原的应用程序中删除所有不需要的快照以释放存储空间。


[CAUTION]
====
在与其他应用程序共享资源的应用程序上执行原位还原操作可能会产生意外结果。对其中一个应用程序执行原位还原时、这些应用程序之间共享的任何资源都会被替换。

====
.步骤
. 选择 * 应用程序 * ，然后选择应用程序的名称。
. 从“操作”列的“选项”菜单中，选择*Restore*。
. 选择还原类型：
+
** *还原到原始命名空间*：使用此操作步骤 将应用程序原位还原到原始集群。
+
... 选择要用于原位还原应用程序的快照或备份、这会将应用程序还原到其自身的早期版本。
... 选择 * 下一步 * 。
+

NOTE: 如果还原到先前已删除的命名空间、则在还原过程中会创建一个同名的新命名空间。任何有权管理先前删除的命名空间中的应用程序的用户都需要手动还原对新重新创建的命名空间的权限。



** *还原到新命名空间*：使用此操作步骤 将应用程序还原到另一个集群或使用与源不同的命名空间。
+
... 指定已还原应用程序的名称。
... 为要还原的应用程序选择目标集群。
... 为与应用程序关联的每个源命名空间输入目标命名空间。
+

NOTE: 作为此还原选项的一部分、Astra Control会创建新的目标命名空间。指定的目标命名空间不能已存在于目标集群上。

... 选择 * 下一步 * 。
... 选择用于还原应用程序的快照或备份。
... 选择 * 下一步 * 。




. 选择要筛选的任何资源：
+
** *恢复所有资源*：恢复与原始应用程序关联的所有资源。
** *过滤资源*：指定规则以还原原始应用程序资源的子集：
+
... 选择在已还原的应用程序中包括或排除资源。
... 选择*添加包含规则*或*添加排除规则*，并配置规则以在应用程序恢复期间过滤正确的资源。您可以编辑或删除规则、然后重新创建规则、直到配置正确为止。
+

NOTE: 要了解有关配置包含和排除规则的信息、请参见 <<在应用程序还原期间筛选资源>>。





. 选择 * 下一步 * 。
. 请仔细查看有关还原操作的详细信息，键入“restore”(如果出现提示)，然后选择*Restore*。


.结果
Astra Control 会根据您提供的信息还原应用程序。如果您已原位还原应用程序、则现有永久性卷的内容将替换为已还原应用程序中的永久性卷的内容。


NOTE: 在执行数据保护操作(克隆、备份或还原)并随后调整永久性卷大小后、在Web UI中显示新卷大小之前、最多会有20分钟的延迟。数据保护操作将在几分钟内成功完成，您可以使用存储后端的管理软件确认卷大小的更改。


NOTE: 任何按命名空间名称/ID或命名空间标签限制命名空间的成员用户都可以将应用程序克隆或还原到同一集群上的新命名空间或其组织帐户中的任何其他集群。但是，同一用户无法访问新命名空间中的克隆或还原应用程序。通过克隆或还原操作创建新命名空间后，帐户管理员 / 所有者可以编辑成员用户帐户并更新受影响用户的角色约束，以授予对新命名空间的访问权限。



== 在应用程序还原期间筛选资源

您可以向添加筛选器规则 link:../use/restore-apps.html["还原"] 此操作将指定要从还原的应用程序中包括或排除的现有应用程序资源。您可以根据指定的命名空间、标签或GVK (GroupVersion Kind)包括或排除资源。

.阅读有关包含和排除方案的更多信息
[%collapsible]
====
* *选择包含原始命名空间的规则(就地还原)*：您在规则中定义的现有应用程序资源将被删除，并替换为用于还原的选定快照或备份中的应用程序资源。未在包含规则中指定的任何资源将保持不变。
* *选择包含新名称空间的规则*：使用此规则在还原的应用程序中选择所需的特定资源。未在包含规则中指定的任何资源将不会包含在已还原的应用程序中。
* *选择包含原始名称空间的排除规则(就地恢复)*：您指定要排除的资源将不会还原、并且保持不变。未指定排除的资源将从快照或备份中还原。如果筛选的资源中包含相应的状态集、则永久性卷上的所有数据都将被删除并重新创建。
* *选择包含新名称空间的排除规则*：使用此规则可选择要从还原的应用程序中删除的特定资源。未指定排除的资源将从快照或备份中还原。


====
规则可以是包含类型、也可以是排除类型。不提供组合使用资源包含和排除的规则。

.步骤
. 选择筛选资源并在恢复应用程序向导中选择包含或排除选项后，选择*添加包含规则*或*添加排除规则*。
+

NOTE: 您不能排除Asta Control自动包含的任何集群范围的资源。

. 配置筛选器规则：
+

NOTE: 必须至少指定一个命名空间、标签或GVK。确保在应用筛选器规则后保留的任何资源足以使已还原的应用程序保持运行状况良好。

+
.. 为规则选择特定命名空间。如果不进行选择、则会在筛选器中使用所有名称空间。
+

NOTE: 如果您的应用程序最初包含多个名称空间、而您将其还原到新的名称空间、则会创建所有名称空间、即使它们不包含资源也是如此。

.. (可选)输入资源名称。
.. (可选)*标签选择器*：包括A https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["标签选择器"^] 以添加到规则中。标签选择器用于仅筛选与选定标签匹配的资源。
.. (可选)选择*使用GVK (GroupVersion Kind)设置来筛选资源*以获取其他筛选选项。
+

NOTE: 如果使用GVK筛选器、则必须指定版本和种类。

+
... (可选)*组*：从下拉列表中选择Kubernetes API组。
... *KND*：从下拉列表中选择要在筛选器中使用的Kubernetes资源类型的对象模式。
... *版本*：选择Kubernetes API版本。




. 查看根据条目创建的规则。
. 选择 * 添加 * 。
+

TIP: 您可以根据需要创建任意数量的资源包含和排除规则。这些规则将显示在启动操作之前的还原应用程序摘要中。


