---
sidebar: sidebar 
permalink: use/set-up-billing.html 
keywords: billing, set up billing, payments, set up payments, credit card, update credit card, change credit card, free plan, free trial, premium, premium plan 
summary: 'Astra Control 的免费计划支持您管理帐户中多达 10 个应用程序。如果您要管理 10 个以上的应用程序，则需要通过从 " 免费计划 " 升级到 " 高级计划 " 来设置计费。' 
---
= 设置计费
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Astra Control 的免费计划支持您管理帐户中多达 10 个应用程序。如果您要管理 10 个以上的应用程序，则需要通过从 " 免费计划 " 升级到 " 高级计划 " 来设置计费。



== 计费概述

使用 Astra Control Service 会产生两种成本：由 NetApp 为 Astra Control Service 收取费用，由云提供商为永久性卷和对象存储收取费用。



=== Astra Control Service 计费

Astra 控制服务提供三个计划：

免费计划:: 免费管理多达 10 个应用程序。
高级 PayGo:: 管理数量不限的应用程序，每个应用程序的速率为每分钟 005 美元。
高级订阅:: 按折扣价预付费，每年订阅一次，您可以在每个应用程序软件包中管理多达 10 个应用程序。请联系 NetApp 销售部门，根据您的组织需要购买任意数量的软件包—例如，从 Astra Control Service 购买 3 个软件包来管理 30 个应用程序。如果您管理的应用程序超过年度订阅所允许的数量，则每个应用程序的超额费用为每分钟 0.005 美元（与高级 PayGo 相同）。
+
--
如果您还没有 Astra Control 帐户，则购买高级订阅会自动为您创建一个 Astra Control 帐户。如果您已有免费计划，则会自动转换为高级订阅。

--


创建 Astra Control 帐户时，您将自动注册免费计划。Astra Control 的信息板显示了您当前管理的 10 个免费应用程序中的多少个应用程序。

如果您尝试管理第 11 个应用程序，则 Astra Control 会通知您已达到免费计划的限制。然后，系统会提示您从免费计划升级到高级计划。

您可以随时升级到高级计划。升级后， Astra Control 会开始为帐户中的 _all_ 受管应用程序收取费用。前 10 个应用程序不会保留在免费计划中。

ifdef::gcp[]



=== Google Cloud 计费

使用 Astra 控制服务管理 GKE- 集群时，持久卷由 NetApp Cloud Volumes Service 提供支持，应用程序的备份存储在 Google Cloud 存储分段中。

* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/costs["查看 Cloud Volumes Service 的定价详细信息"^]。
+
请注意， Astra 控制服务支持所有服务类型和服务级别。您使用的服务类型取决于 https://cloud.netapp.com/cloud-volumes-global-regions#cvsGcp["Google Cloud 地区"^]。

* https://cloud.google.com/storage/pricing["查看 Google Cloud 存储分段的定价详细信息"^]。


endif::gcp[]

ifdef::azure[]



=== Microsoft Azure 计费

使用 Astra 控制服务管理 AKS 集群时， Azure NetApp Files 会为永久性卷提供支持，应用程序的备份会存储在 Azure Blob 容器中。

* https://azure.microsoft.com/en-us/pricing/details/netapp["查看 Azure NetApp Files 的定价详细信息"^]。
* https://azure.microsoft.com/en-us/pricing/details/storage/blobs["查看 Microsoft Azure Blob 存储的定价详细信息"^]。


endif::azure[]

ifdef::aws[]



=== Amazon Web Services计费

使用Astra控制服务管理AWS集群时、永久性卷由EBS或FSX for NetApp ONTAP 提供支持、应用程序的备份存储在AWS存储分段中。

* https://aws.amazon.com/eks/pricing/["查看Amazon Web Services的定价详细信息"^]。


endif::aws[]



== 重要注意事项

* 您的计费计划按 Astra Control 帐户制定。
+
如果您有多个帐户，则每个帐户都有自己的计费计划。

* 您的 Astra Control 费用包括管理 Kubernetes 应用程序的费用。云提供商会为永久性卷的存储后端单独收取费用。
+
link:../get-started/intro.html["了解有关 Astra Control 定价的更多信息"]。

* 每个计费周期都在一个月的最后一天结束。
* 您不能从高级版计划降级到免费版计划。




== 从免费计划升级到高级 PayGo 计划

随时升级您的计费计划，通过按需购买从 Astra Control 开始管理 10 多个应用程序。您只需要一张有效的信用卡即可。

.步骤
. 选择 * 帐户 * ，然后选择 * 账单 * 。
. 在 * 计划 * 下，转到 * 高级 PayGo* 并选择 * 立即升级 * 。
. 提供有效信用卡的付款详细信息，然后选择 * 升级到高级计划 * 。
+

NOTE: 如果信用卡即将到期， Astra Control 将通过电子邮件向您发送电子邮件。



现在，您可以管理 10 多个应用程序。Astra Control 开始为您当前管理的 _all_ 应用程序收费。



== 从免费计划升级到高级订阅

请联系 NetApp 销售部门，以折扣价按年订阅预付费用。

.步骤
. 选择 * 帐户 * ，然后选择 * 账单 * 。
. 在 * 计划 * 下，转到 * 高级订阅 * 并选择 * 联系销售人员 * 。
. 向销售团队提供详细信息以启动此流程。


NetApp 销售代表将与您联系以处理您的采购订单。订单完成后， Astra Control 将在计费选项卡上反映您的当前计划。



== 查看当前成本和计费历史记录

Astra Control 可按应用程序显示您当前的每月成本以及详细的计费历史记录。

.步骤
. 选择 * 帐户 * ，然后选择 * 账单 * 。
+
您的当前成本将显示在计费概述下。

. 要按应用程序查看计费历史记录，请选择 * 计费历史记录 * 。
+
Astra Control 可为您显示每个应用程序的使用分钟数和成本。使用分钟数是 Astra Control 在计费期间管理您的应用程序的分钟数。

. 选择下拉列表以选择上个月。




== 更改 Premium PayGo 的信用卡

如果需要，您可以更改 Astra Control 已记录的用于计费的信用卡。

.步骤
. 选择 * 帐户 > 计费 > 付款方式 * 。
. 选择配置图标。
. 修改信用卡。

