---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster 
summary: 从 Astra Control 中删除不再需要管理的任何应用程序或集群。 
---
= 取消管理应用程序和集群
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
从 Astra Control 中删除不再需要管理的任何应用程序或集群。



== 停止管理应用程序

停止管理不再需要从 Astra Control 备份，创建快照或克隆的应用程序。

取消管理应用程序时：

* 所有现有备份和快照都将被删除。
* 应用程序和数据始终可用。


.步骤
. 从左侧导航栏中，选择 * 应用程序 * 。
. 选择应用程序。
. 从选项菜单的操作列中、选择*取消管理*。
. 查看相关信息。
. 键入 "unmanage" 进行确认。
. 选择 * 是，取消管理应用程序 * 。


.结果
Astra Control 停止管理应用程序。



== 停止管理集群

停止从 Astra Control 管理您不再需要管理的集群。

ifdef::gcp[]


NOTE: 在取消管理集群之前，您应取消管理与集群关联的应用程序。

作为最佳实践，我们建议您先从 Astra Control 中删除集群，然后再通过 GCP 将其删除。

endif::gcp[]

取消管理集群时：

* 此操作将停止由 Astra Control 管理集群。它不会对集群的配置进行任何更改，也不会删除集群。
* Astra Control配置程序或Astra三端存储不会从集群中卸载。 https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["了解如何卸载 Astra Trident"^]。


.步骤
. 选择 * 集群 * 。
. 选中不再需要管理的集群对应的复选框。
. 从“*操作*”列的选项菜单中，选择“*取消管理*”。
. 确认要取消管理此集群、然后选择*是、取消管理*。


.结果
集群状态将更改为*正在删除*。之后，该群集将从*Clusters页中删除，并且不再由Astra Control管理。



== 从云提供商中删除集群

在删除持久性卷（ PV ）驻留在 NetApp 存储类上的 Kubernetes 集群之前，您需要先按照以下方法之一删除永久性卷声明（ PVC ）。在删除集群之前删除PVC和PV可确保您不会收到云提供商的意外账单。

* * 方法 1* ：从集群中删除应用程序工作负载命名空间。请勿删除 Trident 命名空间。
* * 方法 2* ：删除 PVC 和 Pod ，或者删除挂载 PV 的部署。


当您从Astra Control管理Kubernetes集群时、该集群上的应用程序会使用您的云提供商作为永久性卷的存储后端。如果从云提供商中删除集群而未先删除 PV ，则后端卷将与集群一起被删除。

使用上述方法之一将从集群中删除相应的 PV 。在删除集群之前，请确保集群上的 NetApp 存储类中不存在任何 PV 。

如果在删除集群之前未删除永久性卷、则需要手动从云提供程序中删除后端卷。
