---
sidebar: sidebar 
permalink: get-started/add-first-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 设置环境后，您可以创建 Kubernetes 集群，然后将其添加到 Astra Control Service 。 
---
= 从 Astra Control Service 开始管理 Kubernetes 集群
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
设置环境后，您可以创建 Kubernetes 集群，然后将其添加到 Astra Control Service 。



== 创建 Kubernetes 集群

如果您还没有集群，请创建一个满足要求的集群 link:set-up-google-cloud.html#gke-cluster-requirements["Google Kubernetes Engine （ GKEE ）的 Astra Control Service 要求"]， link:set-up-microsoft-azure-with-anf.html["采用 Azure NetApp Files 的 Azure Kubernetes Service （ AKS ）的 Astra 控制服务要求"]或 link:set-up-microsoft-azure-with-amd.html["采用 Azure 受管磁盘的 Azure Kubernetes Service （ AKS ）的 Astra Control Service 要求"] 。



== 开始管理 Kubernetes 集群

登录到 Astra Control Service 后，第一步是开始管理集群。

[NOTE]
====
当 Astra Control 管理集群时，它会跟踪集群的默认 StorageClass 。如果使用 `kubectl` 命令更改 StorageClass ，则 Astra Control 将还原此更改。要更改由 Astra Control 管理的集群中的默认 StorageClass ，请使用以下方法之一：

* 使用 Astra Control API `PUT /managedClusters` Endpoint ，并使用 `DefaultStorageClass` 参数分配其他默认 StorageClass
* 从 Astra Control 管理中删除集群，然后在选择其他默认 StorageClass 后重新添加


====
.您需要什么？ #8217 ；将需要什么
* 对于 GKE- ，您应该拥有具有所需权限的服务帐户的服务帐户密钥文件。 link:../get-started/set-up-google-cloud.html#create-a-service-account["了解如何设置服务帐户"]。
* 对于 AKS ，您应具有包含创建服务主体时 Azure 命令行界面输出的 JSON 文件。 link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["了解如何设置服务主体"]。
+
如果未将 Azure 订阅 ID 添加到 JSON 文件中，您也需要此 ID 。

* 对于专用 AKS 集群：
+
** 集群应满足中所述的要求 https://docs.microsoft.com/en-us/azure/aks/private-clusters["Azure 文档"^]。
** 您需要在 AKS 服务集群上安装 Astra Connector ，以便 Astra Control Service 可以管理此集群。要安装 Astra Connector ， <<Manage a private cluster,请按照以下说明进行操作>>。




.步骤
. 在信息板上，选择 * 管理 Kubernetes 集群 * 。
+
按照提示添加集群。

. * 提供商 * ：选择您的云提供商，然后提供所需的凭据。
+
.. * Microsoft Azure* ：通过上传 JSON 文件或从剪贴板粘贴此 JSON 文件的内容来提供有关 Azure 服务主体的详细信息。
+
JSON 文件应包含创建服务主体时 Azure 命令行界面的输出。它还可以包含您的订阅 ID ，以便自动添加到 Astra 。否则，您需要在提供 JSON 后手动输入 ID 。

.. * Google Cloud Platform* ：通过上传文件或粘贴剪贴板中的内容来提供服务帐户密钥文件。
+
Astra 控制服务使用此服务帐户发现在 Google Kubernetes Engine 中运行的集群。



. * 集群 * ：选择要添加的集群。
+
请仔细查看 " 符合条件 " 选项卡。如果出现警告，请将鼠标悬停在警告上以确定集群是否存在问题描述。例如，它可能会标识集群没有工作节点。

+
如果您选择的集群尚未配置 Cloud Volumes Service for Google Cloud 或 Azure NetApp Files ，则会显示一条警告。此集群未安装和配置 NetApp Trident 。如果要使用其他存储服务，您可以继续添加集群。

+
如果您选择的集群标记有 "private" 图标，则它将使用专用 IP 地址，并且 Astra Control 需要使用 Astra Connector 来管理集群。如果您看到一条消息，指出您需要安装 Astra Connector ， <<Manage a private cluster,请按照以下说明进行操作>> 安装 Astra Connector 并启用集群管理。安装 Astra Connector 后，集群应符合条件，您可以继续添加集群。

. * 存储 * ：选择希望部署到此集群的 Kubernetes 应用程序默认使用的存储类。
+
列表中的每个 Cloud Volumes Service for Google Cloud 服务都会显示价格，性能和弹性信息。此时将显示每个 Azure NetApp Files 服务的性能和弹性信息。对于 Google Persistent Disk 或 Azure 受管磁盘等非 NetApp 存储类，不提供价格，性能和弹性信息。

+
每个存储类均可使用以下服务之一：

+
** https://cloud.netapp.com/cloud-volumes-service-for-gcp["适用于 Google Cloud 的 Cloud Volumes Service"^]
** https://cloud.google.com/persistent-disk/["Google 持久磁盘"^]
** https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Azure 受管磁盘"^]
+
了解更多信息 link:../learn/choose-class-and-size.html["GKE 集群的存储类"] 和 link:../learn/azure-storage.html["AKS 集群的存储类"]。



. * 审核并批准 * ：查看配置详细信息并选择 * 添加集群 * 。


Astra Control Service 会在符合条件的集群上创建用于应用程序备份的对象存储，在集群上创建管理员帐户，并设置您指定的默认存储类。此过程最多可能需要 5 分钟。



== 管理专用集群

您可以使用 Astra Control Service 管理专用 AKS 集群。为此，您需要在专用 AKS 服务集群上安装 Astra Connector 操作员。您可以在添加要管理的集群之前完成此步骤，也可以在系统提示时在添加集群期间完成此步骤。

.步骤
. 为 Astra Connector 运算符创建命名空间。
+
[listing]
----
kubectl create ns astra-connector-operator
----
. 将 `asaconnector_operator.yaml` 文件应用于操作员命名空间。
+
[listing]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. 为专用集群组件创建命名空间。
+
[listing]
----
kubectl create ns astra-connector
----
. 应用 Astra Connector 自定义资源定义（ CRD ）。
+
[listing]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. 检查 Astra 连接器的状态。
+
[listing]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
您应看到类似于以下内容的输出：

+
[listing]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----

