---
sidebar: sidebar 
permalink: get-started/add-first-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 设置环境后，您可以创建 Kubernetes 集群，然后将其添加到 Astra Control Service 。 
---
= 从 Astra Control Service 开始管理 Kubernetes 集群
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
设置环境后，您可以创建 Kubernetes 集群，然后将其添加到 Astra Control Service 。

* <<Create a Kubernetes cluster>>
* <<Start managing Kubernetes clusters>>


ifdef::azure[]

* <<Manage a private cluster>>


endif::azure[]

ifdef::aws[]

* <<Provide cluster access to other users>>


endif::aws[]

* <<Change the default storage class>>




== 创建 Kubernetes 集群

如果您还没有集群，请创建一个满足要求的集群 link:set-up-amazon-web-services.html#eks-cluster-requirements["Amazon Elastic Kubernetes Service (EKS)的Astra Control Service要求"]。如果您还没有集群，请创建一个满足要求的集群 link:set-up-google-cloud.html#gke-cluster-requirements["Google Kubernetes Engine （ GKEE ）的 Astra Control Service 要求"]。如果您还没有集群，请创建一个满足要求的集群 link:set-up-microsoft-azure-with-anf.html["采用 Azure NetApp Files 的 Azure Kubernetes Service （ AKS ）的 Astra 控制服务要求"] 或 link:set-up-microsoft-azure-with-amd.html["采用 Azure 受管磁盘的 Azure Kubernetes Service （ AKS ）的 Astra Control Service 要求"]。


NOTE: Astra控制服务支持使用Azure Active Directory (Azure AD)进行身份验证和身份管理的AKS集群。创建集群时、请按照中的说明进行操作 https://docs.microsoft.com/en-us/azure/aks/managed-aad["正式文档"^] 将集群配置为使用Azure AD。您需要确保集群满足AKS管理的Azure AD集成的要求。



== 开始管理 Kubernetes 集群

登录到 Astra Control Service 后，第一步是开始管理集群。

如果在添加集群时未配置任何卷快照类、则Astra控制服务会尝试安装一个具有默认配置的快照类。

[NOTE]
====
当Astra Control管理集群时、它会跟踪集群的默认存储类。如果使用`kubectl`命令更改存储类、则Astra Control将还原此更改。要更改由Astra Control管理的集群中的默认存储类、请使用以下方法之一：

* 使用Astra Control API `PUT /managedClusters` Endpoint、并使用`DefaultStorageClass`参数分配其他默认存储类。
* 使用Astra Control Web UI分配其他默认存储类。请参见 <<Change the default storage class>>。


====
ifdef::aws[]

* 对于Amazon Web Services、您应拥有包含创建集群的IAM用户凭据的JSON文件。 link:../get-started/set-up-amazon-web-services.html#create-an-iam-user["了解如何创建IAM用户"]。
* 适用于NetApp ONTAP 的Amazon FSX需要Astra Trident。如果您计划使用适用于NetApp ONTAP 的Amazon FSx作为EKS集群的存储后端、请确保已完成 link:set-up-amazon-web-services.html#optional-configure-astra-trident-for-amazon-fsx-for-netapp-ontap["步骤7"] 设置说明。


endif::aws[]

ifdef::gcp[]

* 对于 GKE- ，您应该拥有具有所需权限的服务帐户的服务帐户密钥文件。 link:../get-started/set-up-google-cloud.html#create-a-service-account["了解如何设置服务帐户"]。


endif::gcp[]

ifdef::azure[]

* 对于 AKS ，您应具有包含创建服务主体时 Azure 命令行界面输出的 JSON 文件。 link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["了解如何设置服务主体"]。
+
如果未将 Azure 订阅 ID 添加到 JSON 文件中，您也需要此 ID 。

* 对于专用 AKS 集群：
+
** 集群应满足中所述的要求 https://docs.microsoft.com/en-us/azure/aks/private-clusters["Azure 文档"^]。
** 您需要在 AKS 服务集群上安装 Astra Connector ，以便 Astra Control Service 可以管理此集群。要安装 Astra Connector ， <<Manage a private cluster,请按照以下说明进行操作>>。




endif::azure[]

.步骤
. 在信息板上，选择 * 管理 Kubernetes 集群 * 。
+
按照提示添加集群。

. * 提供商 * ：选择您的云提供商，然后提供所需的凭据。


ifdef::aws[]

. * Amazon Web Services*：上传JSON文件或从剪贴板粘贴JSON文件的内容、以提供有关Amazon Web Services IAM用户帐户的详细信息。
+
JSON文件应包含创建集群的IAM用户的凭据。



endif::aws[]

ifdef::azure[]

. * Microsoft Azure* ：通过上传 JSON 文件或从剪贴板粘贴此 JSON 文件的内容来提供有关 Azure 服务主体的详细信息。
+
JSON 文件应包含创建服务主体时 Azure 命令行界面的输出。它还可以包含您的订阅 ID ，以便自动添加到 Astra 。否则，您需要在提供 JSON 后手动输入 ID 。



endif::azure[]

ifdef::gcp[]

. * Google Cloud Platform* ：通过上传文件或粘贴剪贴板中的内容来提供服务帐户密钥文件。
+
Astra 控制服务使用此服务帐户发现在 Google Kubernetes Engine 中运行的集群。



endif::gcp[]

. * 集群 * ：选择要添加的集群。
+
请仔细查看 " 符合条件 " 选项卡。如果出现警告，请将鼠标悬停在警告上以确定集群是否存在问题描述。例如，它可能会标识集群没有工作节点。

+
如果您选择的集群尚未配置Cloud Volumes Service for Google Cloud、则会显示一条警告。此集群未安装和配置 NetApp Trident 。如果要使用其他存储服务，您可以继续添加集群。

+
请仔细查看 " 符合条件 " 选项卡。如果出现警告，请将鼠标悬停在警告上以确定集群是否存在问题描述。例如，它可能会标识集群没有工作节点。

+
如果您选择的集群尚未配置Amazon Web Services、则会显示一条警告。此集群未安装和配置 NetApp Trident 。如果要使用其他存储服务，您可以继续添加集群。

+
请仔细查看 " 符合条件 " 选项卡。如果出现警告，请将鼠标悬停在警告上以确定集群是否存在问题描述。例如，它可能会标识集群没有工作节点。

+
如果您选择的集群尚未配置Azure NetApp Files 、则会显示一条警告。此集群未安装和配置 NetApp Trident 。如果要使用其他存储服务，您可以继续添加集群。

+
如果您选择的集群标记有 "private" 图标，则它将使用专用 IP 地址，并且 Astra Control 需要使用 Astra Connector 来管理集群。如果您看到一条消息，指出您需要安装 Astra Connector ， <<Manage a private cluster,请按照以下说明进行操作>> 安装 Astra Connector 并启用集群管理。安装 Astra Connector 后，集群应符合条件，您可以继续添加集群。

. * 存储 * ：选择希望部署到此集群的 Kubernetes 应用程序默认使用的存储类。
+
[NOTE]
====
每个云提供商存储服务都会显示以下价格、性能和弹性信息：

ifdef::gcp[]

** Cloud Volumes Service for Google Cloud：价格、性能和弹性信息
** Google Persistent Disk：没有价格、性能或弹性信息


endif::gcp[]

ifdef::azure[]

** Azure NetApp Files ：性能和弹性信息
** Azure受管磁盘：无可用的价格、性能或弹性信息


endif::azure[]

ifdef::aws[]

** Amazon Elastic Block Store：没有价格、性能或弹性信息
** 适用于NetApp ONTAP 的Amazon FSX：没有价格、性能或弹性信息


endif::aws[]

====
+
每个存储类均可使用以下服务之一：



ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["适用于 Google Cloud 的 Cloud Volumes Service"^]
* https://cloud.google.com/persistent-disk/["Google 持久磁盘"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Azure 受管磁盘"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["适用于 NetApp ONTAP 的 Amazon FSX"^]


endif::aws[]

+了解更多信息 link:../learn/aws-storage.html["Amazon Web Services集群的存储类"]。了解更多信息 link:../learn/azure-storage.html["AKS 集群的存储类"]。了解更多信息 link:../learn/choose-class-and-size.html["GKE 集群的存储类"]。

. * 审核并批准 * ：查看配置详细信息并选择 * 添加集群 * 。


Astra Control Service 会在符合条件的集群上创建用于应用程序备份的对象存储，在集群上创建管理员帐户，并设置您指定的默认存储类。此过程最多可能需要 5 分钟。

ifdef::azure[]



== 管理专用集群

您可以使用 Astra Control Service 管理专用 AKS 集群。为此，您需要在专用 AKS 服务集群上安装 Astra Connector 操作员。您可以在添加要管理的集群之前完成此步骤，也可以在系统提示时在添加集群期间完成此步骤。

.步骤
. 为 Astra Connector 运算符创建命名空间。
+
[listing]
----
kubectl create ns astra-connector-operator
----
. 将 `asaconnector_operator.yaml` 文件应用于操作员命名空间。
+
[listing]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. 为专用集群组件创建命名空间。
+
[listing]
----
kubectl create ns astra-connector
----
. 应用 Astra Connector 自定义资源定义（ CRD ）。
+
[listing]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. 检查 Astra 连接器的状态。
+
[listing]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
您应看到类似于以下内容的输出：

+
[listing]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----


endif::azure[]

ifdef::aws[]



== 为其他用户提供集群访问权限

您可以选择为集群提供`kubectl`命令访问权限、使其访问不是集群创建者的其他IAM用户。

有关说明，请参见 https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/["在Amazon EKS中创建集群后、如何为其他IAM用户和角色提供访问权限？"^]。

endif::aws[]



== 更改默认存储类

您可以更改集群的默认存储类。

.步骤
. 在 Astra 控制服务 UI 中，选择 * 集群 * 。
. 在*集群*页面上、选择要更改的集群。
. 选择 * 存储 * 选项卡。
. 选择*存储类*类别。
. 选择要设置为默认值的存储类的*操作*菜单。
. 选择*设置为默认值*。

