---
sidebar: sidebar 
permalink: get-started/check-astra-trident-version.html 
keywords: astra trident, check, version, astra control provisioner 
summary: 对于自行管理的集群、您可能需要确保使用正确的Asta三端技术支持版本。 
---
= 检查Asta三端安装版本
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
要添加使用Asta Control置备程序或Asta三端对存储服务使用的自管理集群、请确保已安装的Asta三端对等版本为23.10或最新版本。

.步骤
. 确定您正在运行的Astra三项目标版本：
+
[source, console]
----
kubectl get tridentversions -n trident
----
+
如果安装了Astra Trident、则会显示类似于以下内容的输出：

+
[listing]
----
NAME      VERSION
trident   24.02.0
----
+
如果未安装Astra Trident、您将看到类似于以下内容的输出：

+
[listing]
----
error: the server doesn't have a resource type "tridentversions"
----
. 执行以下操作之一：
+
** 如果您运行的是Asta三端凹凸版23.01或更早版本、请使用这些版本 https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html["说明"^] 在升级到Asta Control配置程序之前、升级到Asta三端到最新版本。您可以 link:../use/enable-acp.html["执行直接升级"] 如果您的Astra三端存储在版本24.02的四个版本的窗口中、则将Astra Control配置程序更新为24.02。例如、您可以直接从Asta三端23.04升级到Asta Control配置程序24.02。
** 如果您运行的是Astra Trdent 23.10或更高版本、请验证Astra Control配置程序是否已启用 link:../use/faq.html#running-acp-check["enabled"]。Asta Control配置程序不能用于23.10之前的Asta Control Center版本。 link:../get-started/enable-acp.html["升级Astra Control配置程序"] 以便它与您要升级的Astra Control Center版本相同、以访问最新功能。


. 确保Pod正在运行：
+
[source, console]
----
kubectl get pods -n trident
----
. 检查存储类是否正在使用受支持的Astra Trident驱动程序。配置程序名称应为 `csi.trident.netapp.io`。请参见以下示例：
+
[source, console]
----
kubectl get sc
----
+
响应示例：

+
[listing]
----
NAME                   PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ontap-gold (default)   csi.trident.netapp.io          Delete          Immediate           true                   5d23h
----

