---
sidebar: sidebar 
permalink: get-started/faq.html 
keywords: faq, frequently asked questions 
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= 有关 Astra 控制服务的常见问题
:hardbreaks:
:icons: font
:imagesdir: ../media/


如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 概述

Astra Control 旨在简化 Kubernetes 原生应用程序的应用程序数据生命周期管理操作。Astra 控制服务支持在 Google Kubernetes Engine （ GKEE ）和 Azure Kubernetes Service （ AKS ）上运行的 Kubernetes 集群。

以下各节将为您在使用 Astra Control 时可能遇到的其他一些问题提供解答。如有任何其他澄清，请联系 astra.feedback@netapp.com



== 访问 Astra Control

* 注册 Astra Control 时，为什么需要提供如此多的详细信息？ *

Astra Control 在注册时需要准确的客户信息。要进行全球贸易合规性（ GTC ）检查，必须提供此信息。

* 注册 Astra Control 时为什么会出现 " 注册失败 " 错误？ *

Astra Control 要求您在入职部分提供准确的客户信息。如果您提供的信息不正确，则会收到 "Registration Failed" 错误。您所属的其他帐户也会被锁定。

* 什么是 Astra 控制服务 URL ？ *

您可以通过访问 Astra 控制服务 https://astra.netapp.io[]。

* 我向同事发送了一封电子邮件邀请函，但他们尚未收到。我该怎么办？ *

要求他们检查其垃圾邮件文件夹中是否有来自 do-not-reply@netapp.com 的电子邮件，或者在收件箱中搜索 " 邀请函 " 。 您也可以删除此用户并尝试重新添加它们。

* 我已从免费计划升级到高级 PayGO 计划。我是否会为前 10 个应用程序付费？ *

是的。升级到高级计划后， Astra Control 开始为您帐户中的所有受管应用程序收取费用。

* 我在一个月中升级到高级 PayGO 计划。我是否会在整个月内支付费用？ *

不可以，从升级到高级计划开始计费。

* 我正在使用免费计划，是否会为永久性卷申请付费？ *

是的，您需要为 Cloud Volumes Service for Google Cloud 中的 GKS 集群或 Azure NetApp Files 中的 AKS 集群使用的永久性卷付费。



== 注册 Kubernetes 集群

* 在将集群添加到 Astra Control Service 之前，是否需要在集群上安装 CSI 驱动程序？ *

否将集群添加到 Astra Control 后，该服务将自动在 Kubernetes 集群上安装 NetApp 的 Trident 容器存储接口（ Trident Container Storage Interface ， CSI ）驱动程序。此 CSI 驱动程序用于为 NetApp Cloud Volumes Service for Google Cloud 支持的 GKS 集群和 Azure NetApp Files 支持的 AKS 集群配置永久性卷。

* 添加到 Astra Control Service 后，我需要向集群添加工作节点。我该怎么办？ *

可以将新的工作节点添加到现有池中，也可以创建新池，只要它们是 Ubuntu 映像类型即可。这些信息将由 Astra Control 自动发现。如果新节点在 Astra Control 中不可见，请检查新工作节点是否正在运行受支持的映像类型。您也可以使用 `kubectl get nodes` 命令验证新工作节点的运行状况。



== 注册 GKEE 集群

* 是否可以将专用 GKEE 集群添加到 Astra Control Service ？ *

可以，您可以将专用集群添加到 Astra Control Service 。要创建 Google Kubernetes Engine （ GKEE ）专用集群， https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Project_Astra/How_to_create_a_private_GKE_cluster_to_work_with_project_Astra["按照此知识库文章中的说明进行操作"^]。

专用集群必须具有 https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept["授权网络"^] 设置为允许 Astra Control IP 地址：

* 54.164.233.140/32
* 3.218.120.204/32
* 34.193.99.138/32


* 我的 GKE 集群是否可以位于共享 VPC 上？ *

可以， Astra Control 可以管理位于共享 VPC 中的集群。 link:set-up-google-cloud.html["了解如何为共享 VPC 配置设置 Astra 服务帐户"]。

在 GCP 上的何处可以找到我的服务帐户凭据？ *

登录到后 https://console.cloud.google.com/["Google Cloud Console"^]，您的服务帐户详细信息将显示在 * IAM 和管理 * 部分中。有关详细信息，请参见 link:set-up-google-cloud.html["如何为 Astra Control 设置 Google Cloud"]。

* 我想从不同的 GCP 项目添加不同的 GKEE 集群。Astra Control 是否支持此功能？ *

不支持，此配置不受支持。仅支持一个 GCP 项目。



== 删除集群

* 如何正确取消注册，关闭集群以及删除关联的卷？ *

. link:../use/unmanage.html["从 Astra Control 取消管理应用程序"]。
. link:../use/unmanage.html#stop-managing-compute["从 Astra Control 中取消注册集群"]。
. link:../use/unmanage.html#deleting-clusters-from-your-cloud-provider["删除永久性卷声明"]。
. 删除集群。


* 从 Astra Control 中删除集群后，应用程序和数据会发生什么情况？ *

从 Astra Control 中删除集群不会对集群的配置（应用程序和永久性存储）进行任何更改。对该集群上的应用程序执行的任何 Astra Control 快照或备份都将无法还原。存储在后端存储中的卷快照数据不会被删除。由 Astra Control 创建的永久性存储备份将保留在云提供商的对象存储中，但无法还原。


WARNING: 在通过 GCP 删除集群之前，请始终从 Astra Control 中将其删除。如果在集群仍由 Astra Control 管理时从 GCP 中删除集群，则可能会对您的 Astra Control 帐户产生发生原因问题。

* 从 Astra Control 中删除集群时是否会卸载 Astra Trident ？ *

从 Astra Control 中删除 Astra Trident 后，它不会从集群中卸载。



== 管理应用程序

* Astra Control 是否可以部署应用程序？ *

Astra Control 不会部署应用程序。应用程序必须部署在 Astra Control 之外。

* 我的应用程序未显示在发现的应用程序列表中。我可以检查哪些内容来确定问题？ *

如果应用程序未列在 * 已发现应用程序 * 中，请运行 `kubectl get pod -a |grep [pod name]` 以检查 Kubernetes Pod 的状态和运行状况。如果 Pod 运行状况良好且正在运行，请检查此应用程序是否列在 * 忽略的应用程序 * 下。

* Astra Control 是否可以管理非 NetApp 存储上的应用程序？ *

否虽然 Astra Control 可以发现使用非 NetApp 存储的应用程序，但它无法管理使用非 NetApp 存储的应用程序。

* 我看不到应用程序的任何 PVC 绑定到 GCP CVS 。有什么问题？ *

在成功添加到 Astra Control 后， Astra Trident 运算符会将默认存储类设置为 `NetApp-CVS-Premium` 。如果应用程序的 PVC 未绑定到适用于 Google Cloud 的 Cloud Volumes Service ，您可以执行以下几个步骤：

* 运行 `kubectl get SC` 并检查默认存储类。
* 检查用于部署应用程序的 YAML 文件或 Helm 图表，查看是否定义了其他存储类。
* 检查以确保工作节点映像类型为 Ubuntu 且 NFS 挂载成功。


* 停止从 Astra Control 管理应用程序后，应用程序会发生什么情况？ *

任何现有备份或快照都将被删除。应用程序和数据始终可用。数据管理操作不适用于非受管应用程序或属于该应用程序的任何备份或快照。



== 数据管理操作

* Astra Control 在何处创建对象存储分段？ *

第一个受管集群的地理位置决定了对象存储的位置。例如，如果您添加的第一个集群位于欧洲区域，则会在同一地理位置创建存储分段。如果需要，您可以 link:../use/manage-buckets.html["添加其他存储分段"]。

* 我的帐户中存在未创建的快照。它们来自何处？ *

在某些情况下， Astra Control 会在执行其他过程时自动创建快照。如果这些快照的使用时间超过几分钟，您可以安全地将其删除。

* 我的应用程序使用多个 PV 。Astra Control 是否会为所有这些 PVC 创建快照和备份？ *

是的。Astra Control 对应用程序执行的快照操作包括绑定到应用程序 PVC 的所有 PV 的快照。

* 是否可以直接通过云提供商管理 Astra Control 创建的快照？ *

否Astra Control 创建的快照和备份只能使用 Astra Control 进行管理。
