---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview 
summary: Astra Control 是 Kubernetes 应用程序数据生命周期管理解决方案，可简化有状态应用程序的操作。轻松保护，备份和迁移 Kubernetes 工作负载，并即时创建有效的应用程序克隆。 
---
= Astra Control 简介
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/


Astra Control 是 Kubernetes 应用程序数据生命周期管理解决方案，可简化有状态应用程序的操作。轻松保护，备份和迁移 Kubernetes 工作负载，并即时创建有效的应用程序克隆。



== 功能

Astra Control 为 Kubernetes 应用程序数据生命周期管理提供了关键功能：

* 自动管理永久性存储
* 创建应用程序感知型按需快照和备份
* 自动执行策略驱动的快照和备份操作
* 将应用程序和数据从一个 Kubernetes 集群迁移到另一个集群
* 轻松地将应用程序从生产环境克隆到暂存环境
* 直观显示应用程序运行状况和保护状态
* 使用用户界面或 API 实施备份和迁移工作流




== 部署模式

Astra Control 有两种部署模式：

* * Astra Control Service* ： NetApp 管理的一项服务，可在 Google Kubernetes Engine （ GKEE ）和 Azure Kubernetes Service （ AKS ）中为 Kubernetes 集群提供应用程序感知型数据管理。
* * Astra Control Center* ：自管理软件，可为内部环境中运行的 Kubernetes 集群提供应用程序感知型数据管理。


[cols="1h,2d,2d"]
|===
|  | Astra 控制服务 | Astra 控制中心 


| 如何提供？ | 作为 NetApp 提供的一项完全托管的云服务 | 作为您下载，安装和管理的软件 


| 它托管在何处？ | 基于 NetApp 选择的公有云 | 在您提供的 Kubernetes 集群上 


| 如何更新？ | 由 NetApp 管理 | 您可以管理任何更新 


| 应用程序数据管理功能是什么？ | 两个平台上的功能相同，但后端存储或外部服务除外 | 两个平台上的功能相同，但后端存储或外部服务除外 


| 什么是后端存储支持？ | NetApp 云服务产品 | NetApp ONTAP AFF 和 FAS 系统 
|===


== 支持的应用程序

Astra Control 支持 Kubernetes 集群上运行的所有应用程序。NetApp 已对某些应用程序进行了验证，以确保快照和备份的安全性和一致性。

link:../learn/validated-vs-standard.html["了解经过验证的应用程序与标准应用程序之间的区别"]。

无论与 Astra Control 结合使用哪种类型的应用程序，您都应始终自行测试备份和还原工作流，以确保满足灾难恢复要求。



== Astra 控制服务的工作原理

Astra Control Service 是一种由 NetApp 管理的云服务，它始终处于启用状态，并使用最新功能进行更新。它利用多个组件实现应用程序数据生命周期管理。

从较高的层面来看， Astra Control Service 的工作原理如下：

* 您可以通过设置云提供商并注册 Astra 帐户开始使用 Astra Control Service 。
+
** 对于 GKE- 集群， Astra Control Service 使用 https://cloud.netapp.com/cloud-volumes-service-for-gcp["适用于 Google Cloud 的 NetApp Cloud Volumes Service"^] 作为永久性卷的后端存储。
** 对于 AKS 集群， Astra Control Service 使用 https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^] 作为永久性卷的后端存储。


* 您可以将第一个 Kubernetes 计算添加到 Astra Control Service 中。然后， Astra 控制服务将执行以下操作：
+
** 在云提供商帐户中创建一个对象存储，该帐户是备份副本的存储位置。
+
在 Azure 中， Astra Control Service 还会为 Blob 容器创建资源组，存储帐户和密钥。

** 在集群上创建新的管理员角色和 Kubernetes 服务帐户。
** 使用此新管理员角色进行安装 https://netapp-trident.readthedocs.io/["NetApp 的 Trident"^] 以创建一个或多个存储类。
** 使用 Trident 为应用程序配置永久性卷。


* 此时，您可以向集群添加应用程序。将在新的默认存储类上配置永久性卷。
+
** link:../learn/choose-class-and-size.html["了解 GKEE 集群的存储类"]。
** link:../learn/azure-storage.html["了解 AKS 集群的存储类"]。


* 然后，您可以使用 Astra Control Service 管理这些应用程序，并开始创建快照，备份和克隆。
+
Astra Control Service 会持续监控您的计算状态变化，因此它可以识别您在此过程中添加的任何新应用程序。



Astra Control 的免费计划支持您管理帐户中多达 10 个应用程序。如果您要管理 10 个以上的应用程序，则需要 link:../use/set-up-billing.html["通过从免费计划升级到高级计划来设置计费"]。



== Astra 控制中心的工作原理

Astra 控制中心在您自己的私有云中本地运行。

对于第一个版本， Astra 控制中心将支持 ONTAP 9.5 及更高版本的 OpenShift Kubernetes 集群和 Trident 存储后端。

在云互联环境中， Astra 控制中心使用 Cloud Insights 提供高级监控和遥测功能。如果没有 Cloud Insights 连接，则 Astra 控制中心可提供有限的（ 7 天的指标）监控和遥测功能，并通过开放式指标端点导出到 Kubernetes 原生监控工具（例如 Prometheus 和 Grafana ）。

Astra 控制中心完全集成到 AutoSupport 和 Active IQ 生态系统中，可为用户和 NetApp 支持提供故障排除和使用信息。

您可以使用 90 天评估许可证试用 Astra Control Center 。评估版可通过电子邮件和社区（ Slack 通道）选项来支持。此外，您还可以从产品支持信息板访问知识库文章和文档。

要安装和使用 Astra 控制中心，您需要满足特定的要求 https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html["要求"^]。

从较高的层面来看， Astra 控制中心的工作原理如下：

* 您可以在本地环境中安装 Astra Control Center 。详细了解如何操作 https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html["安装 Astra 控制中心"^]。
* 您可以完成一些设置任务，例如：
+
** 设置许可
** 添加第一个集群。
** 添加在添加集群时发现的后端存储。
** 添加用于存储应用程序备份的对象存储分段。




详细了解如何操作 https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html["设置 Astra 控制中心"^]。

Astra 控制中心可执行以下操作：

* 发现有关受管 Kubernetes 集群的详细信息。
* 在您选择管理的集群上发现 Trident 配置，并可用于监控存储后端。
* 发现这些集群上的应用程序，并使您能够管理和保护这些应用程序。


您可以将应用程序添加到集群中。或者，如果要管理的集群中已有一些应用程序，则可以使用 Astra 控制中心来发现和管理它们。然后，使用 Astra 控制中心创建快照，备份和克隆。
