---
sidebar: sidebar 
permalink: get-started/manage-private-cluster.html 
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster 
summary: 设置环境后，您可以创建 Kubernetes 集群，然后将其添加到 Astra Control Service 。 
---
= 通过Astra Control Service管理专用集群
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
您可以使用 Astra Control Service 管理专用 AKS 集群。以下说明假定您已创建专用AKS集群并准备了一种远程访问此集群的安全方法；有关创建和访问专用AKS集群的详细信息、请参见 https://docs.microsoft.com/azure/aks/private-clusters["Azure 文档"^]。

* <<安装Astra Connector操作员>>
* <<设置永久性存储>>
* <<将专用集群添加到Astra Control Service>>




== 安装Astra Connector操作员

您需要在专用AKS集群上安装Astra Connector操作员。如果使用的是Bastion主机、请从Bastion主机的命令行对这些命令执行问题描述。

.步骤
. 克隆Astra Connector操作员GitHub存储库：
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. 将目录更改为已解压缩运算符包的顶层、以便您可以使用`ls`命令查看`astor_operator.yaml`文件。
. 为 Astra Connector 运算符创建命名空间。
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. 将 `asaconnector_operator.yaml` 文件应用于操作员命名空间。
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. 为专用集群组件创建命名空间。
+
[source, console]
----
kubectl create ns astra-connector
----
. 按照中的说明生成Astra Control API令牌 https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html["Astra Automation文档"^]。
. 根据需要修改Astra Connector操作员存储库的config/samples目录中的示例配置文件。
. 应用 Astra Connector 自定义资源定义（ CRD ）。
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. 检查 Astra 连接器的状态。
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
您应参考类似于以下内容的输出：

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== 设置永久性存储

为集群配置永久性存储。您可以使用Azure NetApp Files 或Azure受管磁盘。有关使用以下选项配置Azure的详细信息、请参见入门文档：

* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-anf.html["使用 Azure NetApp Files 设置 Microsoft Azure"]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html["使用 Azure 受管磁盘设置 Microsoft Azure"]




== 将专用集群添加到Astra Control Service

现在、您可以将专用AKS集群添加到Astra Control Service。按照标准工作流将集群添加到Astra Control Service： https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html["从 Astra Control Service 开始管理 Kubernetes 集群"]。
