---
sidebar: sidebar 
permalink: get-started/register.html 
keywords: BlueXP, sign up, log in, login, register, register for BlueXP, create account, sign up for account, get an account, account, accounts 
summary: Astra控制服务集成在NetApp BlueXP的身份验证服务中。注册BlueXP、即可访问Astra Control Service和NetApp的其他云服务。 
---
= 注册 Astra Control Service 帐户
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
要使用Astra控制服务、您需要一个与您的NetApp BlueXP帐户关联的Astra控制服务帐户。完成Astra Control Service注册过程、然后、如果您还没有BlueXP帐户、请注册BlueXP以访问Astra Control Service。



== 注册 Astra Control 帐户

在登录到 Astra 控制服务之前，您需要完成注册过程才能获取 Astra 控制服务帐户。

使用 Astra Control Service 时，您可以从帐户中管理应用程序。帐户包括可以查看和管理帐户中的应用程序以及您的计费详细信息的用户。

.步骤
. https://cloud.netapp.com/astra["转到BlueXP上的Asta Control页面"^]。
. 选择*立即开始*。
. 在表单中提供所需信息。
+
填写表单时需要注意的一些重要事项：

+
** 您的企业名称和地址必须准确无误，因为我们会对其进行验证，以满足全球贸易合规性的要求。
** * Astra 帐户名称 * 是您企业的 Astra Control Service 帐户的名称。您将在 Astra Control Service 用户界面中看到此名称。请注意，如果需要，您可以创建其他帐户（最多 5 个）。
** 在*企业电子邮件地址*字段中，如果您有NetApp BlueXP帐户，请在此处输入用于该帐户的电子邮件。如果您还没有NetApp BlueXP帐户、请使用注册BlueXP时在此处输入的电子邮件地址。


. 选择 * 创建帐户 * 。




== 注册到BlueXP

Astra控制服务集成在NetApp BlueXP的身份验证服务中。您可以使用BlueXP或NetApp NetApp 支持站点 凭据登录到BlueXP。如果您还没有NetApp BlueXP或NetApp 支持站点 帐户、请注册BlueXP、以便访问Astra Control服务和NetApp的其他云服务。如果您已有BlueXP或NetApp 支持站点 帐户并已完成注册、则可以访问 https://astra.netapp.io["Astra 控制服务"^] 直接使用BlueXP或NetApp 支持站点 凭据。


TIP: 您还可以使用公司目录中的凭据(联合身份)通过单点登录登录到BlueXP。要了解更多信息，请转到 https://cloud.netapp.com/help-center["帮助中心"^] 然后选择 * Cloud Central 登录选项 * 。

.步骤
. 转至 https://cloud.netapp.com["NetApp BlueXP"^]。
. 在右上角，选择*Get started*。
. 选择 * 注册 * 。
. 填写表单。
+
确保您在此处输入的电话号码和电子邮件地址与您在前一个Astra Control注册表中使用的地址相同。

. 选择 * 注册 * 。
+

TIP: 您在这些表单中输入的电子邮件地址是您的NetApp BlueXP用户ID的电子邮件地址。当您注册新的Astra Control帐户或Astra Control管理员邀请您加入现有Astra Control帐户时、请使用此BlueXP用户ID。

. 等待NetApp BlueXP发送的电子邮件。此电子邮件来自地址 saas.support@netapp.com ，可能需要几分钟才能收到。请务必检查您的垃圾邮件文件夹。
. 电子邮件到达后，选择电子邮件中的链接以验证您的电子邮件地址。


.结果
现在、您已拥有有效的BlueXP用户登录名。

注册后、您可以直接从使用BlueXP凭据访问ASRA Control https://astra.netapp.io[]。
