---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: limitations, known limitations, interoperability 
summary: 已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。



== 一般限制

以下限制会影响 Astra Control Service 在任何受支持的 Kubernetes 部署中对 Kubernetes 集群的管理。



=== 未从集群中卸载Astra Trident

从 Astra 控制服务取消管理集群时，不会自动从集群中卸载 Astra Trident 。要卸载 Astra Trident ，您需要 https://["请按照 Astra Trident 文档中的以下步骤进行操作"^]。



=== 与 Postgres Pod 的现有连接导致故障

在 Postgres Pod 上执行操作时，不应直接在 Pod 中连接以使用 psql 命令。Astra 控制服务需要使用 psql 访问权限来冻结和解冻数据库。如果已建立连接，则快照，备份或克隆将失败。



=== "Activity"页面最多可显示100、000个事件

Astra Control Activity页面最多可显示100、000个事件。要查看所有记录的事件、请使用检索这些事件 link:../rest-api/api-intro.html["Astra Control REST API"^]。

ifdef::gcp[]



== GKEE 集群管理的限制

以下限制适用于在 Google Kubernetes Engine （ GKEE ）中管理 Kubernetes 集群。



=== Google Marketplace应用程序尚未经过验证

NetApp 尚未验证从 Google Marketplace 部署的应用程序。一些用户报告了从Google Marketplace部署的Postgre、MariaDB和MySQL应用程序的发现或备份问题。

无论您在 Astra Control Service 中使用哪种类型的应用程序，您都应始终自行测试备份和还原工作流，以确保满足灾难恢复要求。

endif::gcp[]



== 应用程序管理限制

以下限制会影响 Astra Control Service 对应用程序的管理。



=== 使用同一命名空间的多个应用程序不能一起还原到不同的命名空间

如果您通过在Astra Control中创建多个应用程序定义来管理多个使用同一命名空间的应用程序、则无法将所有应用程序还原到另一个命名空间。您需要将每个应用程序还原到其自己单独的命名空间。



=== Astra Control不会自动为云实例分配默认分段

Astra Control不会自动为任何云实例分配默认分段。您需要手动设置云实例的默认存储分段。如果未设置默认分段、您将无法在两个集群之间执行应用程序克隆操作。



=== 不支持对使用证书管理器的应用程序执行原位还原操作

此版本的Astra控制服务不支持使用证书管理器原位还原应用程序。支持将还原操作还原到其他命名空间和克隆操作。



=== 使用设置的存储类部署应用程序后，应用程序克隆将失败

在使用显式设置的存储类（例如， `helm install ...-set global.storageClass=netapp-cvs-perf-至 至至` ）部署应用程序后，后续克隆应用程序的尝试要求目标集群具有最初指定的存储类。将具有显式设置的存储类的应用程序克隆到没有相同存储类的集群将失败。此情况下没有恢复步骤。



=== 使用 Ppass by reference operators 安装的应用程序克隆可能会失败

Astra Control 支持使用命名空间范围的运算符安装的应用程序。这些操作员通常采用 " 按价值传递 " 架构，而不是 " 按参考传递 " 架构。以下是一些遵循这些模式的操作员应用程序：

* https://["Apache K8ssandra"^]
+

NOTE: 对于 K8ssandra ，支持原位还原操作。要对新命名空间或集群执行还原操作，需要关闭应用程序的原始实例。这是为了确保传输的对等组信息不会导致跨实例通信。不支持克隆应用程序。

* https://["Jenkins CI"^]
* https://["Percona XtraDB 集群"^]


请注意、Astra Control可能无法克隆使用"按参考传递"架构设计的运算符(例如CockroachDB运算符)。在这些类型的克隆操作期间，克隆的操作员会尝试引用源操作员提供的 Kubernetes 机密，尽管在克隆过程中他们拥有自己的新机密。克隆操作可能会失败，因为 Astra Control 不知道源运算符中的 Kubernetes 密钥。


NOTE: 在克隆操作期间、需要IngressClass资源或webhooks才能正常运行的应用程序不能在目标集群上定义这些资源。



== 基于角色的访问控制（ Role-Based Access Control ， RBAC ）限制

以下限制适用于 Astra Control 限制用户访问资源或功能的方式。



=== 具有命名空间 RBAC 限制的用户可以添加和取消管理集群

不应允许具有命名空间 RBAC 限制的用户添加或取消管理集群。由于当前的限制， Astra 不会阻止此类用户取消管理集群。



=== 具有命名空间约束的成员用户无法访问克隆或还原的应用程序，除非管理员用户将命名空间添加到此限制中

受命名空间名称/ID约束的任何`m成员`用户均可将应用程序克隆或还原到同一集群上的新命名空间或其组织帐户中的任何其他集群。但是，同一用户无法访问新命名空间中的克隆或还原应用程序。通过克隆或还原操作创建新命名空间后，帐户管理员 / 所有者可以编辑 `m成员` 用户帐户并更新受影响用户的角色约束，以授予对新命名空间的访问权限。
