---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: 已知问题可确定可能妨碍您成功使用此版本产品的问题。 
---
= 已知问题
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
已知问题可确定可能妨碍您成功使用此版本产品的问题。

以下已知问题会影响当前版本：

.应用程序
*  clones fail after an application is deployed with a set storage class
*  page loads forever when trying to restore an application belonging to a deleted cluster
*  to define an app on a namespace that has been deleted and recreated


.备份，还原和克隆
*  of an app results in PV size larger than original PV
*  clones fail using a specific version of PostgreSQL
*  backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed


.其他问题
*  eventually begin to fail when using external-snapshotter version 4.2.0
*  data management operations fail with Internal Service Error (500) when Astra Trident is offline




== 使用设置的存储类部署应用程序后，应用程序克隆将失败

在使用显式设置的存储类（例如， `helm install ...-set global.storageClass=netapp-cvs-perf-至 至至` ）部署应用程序后，后续克隆应用程序的尝试要求目标集群具有最初指定的存储类。将具有显式设置的存储类的应用程序克隆到没有相同存储类的集群将失败。此情况下没有恢复步骤。



== 尝试还原属于已删除集群的应用程序时、应用程序页面将永久加载

当您尝试从"应用程序"页面中的已删除集群还原应用程序时、"应用程序"页面永远不会完成加载。作为临时解决策 、从应用程序列表页面中的应用程序操作菜单还原应用程序。



== 无法在已删除并重新创建的命名空间上定义应用程序

如果使用命名空间定义应用程序、删除命名空间、然后在同一命名空间中重新安装此应用程序、则此操作将失败、并显示409错误代码。要使用重新创建的命名空间定义应用程序、请先删除旧应用程序实例。



== 还原应用程序会导致 PV 大小大于原始 PV

如果在创建备份后调整永久性卷的大小，然后从该备份还原，则此永久性卷的大小将与 PV 的新大小匹配，而不是使用备份的大小。



== 使用特定版本的 PostgreSQL 时应用程序克隆失败

使用 BitNami PostgreSQL 11.5.0 图表时，同一集群中的应用程序克隆始终会失败。要成功克隆，请使用图表的早期或更高版本。



== 如果在管理集群后添加了volumesnapshotclass、则应用程序备份和快照将失败

在这种情况下、备份和快照失败、并显示UI 500错误。作为临时解决策 、刷新应用程序列表。



== 使用外部快照程序 4.2.0 版时，快照最终开始失败

如果将 Kubernetes Snapshot-controller （也称为外部快照程序） 4.2.0 与 Kubernetes 1.20 或 1.21 结合使用，则快照最终可能会开始失败。要防止出现这种情况，请使用其他 https://kubernetes-csi.github.io/docs/snapshot-controller.html["支持的版本"^] 使用 Kubernetes 版本 1.20 或 1.21 的外部快照程序，例如 4.2.1 版。



== 当 Astra Trident 脱机时，应用程序数据管理操作失败，并显示内部服务错误（ 500 ）

如果应用程序集群上的 Astra Trident 脱机（并恢复联机），并且在尝试应用程序数据管理时遇到 500 个内部服务错误，请重新启动应用程序集群中的所有 Kubernetes 节点以还原功能。
