---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: 已知问题可确定可能妨碍您成功使用此版本产品的问题。 
---
= 已知问题
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
已知问题可确定可能妨碍您成功使用此版本产品的问题。

以下已知问题会影响当前版本：

.应用程序
* <<无法在已删除并重新创建的命名空间上定义应用程序>>


.备份，还原和克隆
* <<使用特定版本的 PostgreSQL 时应用程序克隆失败>>
* <<如果在管理集群后添加了volumesnapshotclass、则应用程序备份和快照将失败>>
* <<对ONTAP NAS经济型存储类的原位还原操作失败>>
* <<使用Kerberos传输中加密时从备份还原可能会失败>>
* <<对于保留策略已过期的存储分段、删除后备份数据仍会保留在存储分段中>>


.其他问题
* <<当 Astra Trident 脱机时，应用程序数据管理操作失败，并显示内部服务错误（ 500 ）>>




== 无法在已删除并重新创建的命名空间上定义应用程序

如果使用命名空间定义应用程序、删除命名空间、然后在同一命名空间中重新安装此应用程序、则此操作将失败、并显示409错误代码。要使用重新创建的命名空间定义应用程序、请先删除旧应用程序实例。



== 使用特定版本的 PostgreSQL 时应用程序克隆失败

使用 BitNami PostgreSQL 11.5.0 图表时，同一集群中的应用程序克隆始终会失败。要成功克隆，请使用图表的早期或更高版本。



== 如果在管理集群后添加了volumesnapshotclass、则应用程序备份和快照将失败

在这种情况下、备份和快照失败、并显示UI 500错误。作为临时解决策 、刷新应用程序列表。



== 对ONTAP NAS经济型存储类的原位还原操作失败

如果您对应用程序执行原位还原(将应用程序还原到其原始命名空间)、并且应用程序的存储类使用 `ontap-nas-economy` 驱动程序、如果未隐藏快照目录、则还原操作可能会失败。在原位还原之前、请按照中的说明进行操作 link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["为ONTAP NAS经济型操作启用备份和还原"^] 以隐藏快照目录。



== 使用Kerberos传输中加密时从备份还原可能会失败

将应用程序从备份还原到使用Kerberos传输中加密的存储后端时、还原操作可能会失败。此问题描述不会影响从快照还原或使用NetApp SnapMirror复制应用程序数据。


NOTE: 在对NFSv4卷使用Kerberos传输中加密时、请确保NFSv4卷使用正确的设置。请参阅的NetApp NFSv4域配置一节(第13页) https://www.netapp.com/media/16398-tr-3580.pdf["《NetApp NFSv4增强功能和最佳实践指南》"^]。



== 对于保留策略已过期的存储分段、删除后备份数据仍会保留在存储分段中

如果在存储分段的保留策略过期后删除应用程序的不可更改备份、则备份将从Astra Control中删除、而不是从存储分段中删除。此问题描述将在即将发布的版本中予以修复。



== 当 Astra Trident 脱机时，应用程序数据管理操作失败，并显示内部服务错误（ 500 ）

如果应用程序集群上的 Astra Trident 脱机（并恢复联机），并且在尝试应用程序数据管理时遇到 500 个内部服务错误，请重新启动应用程序集群中的所有 Kubernetes 节点以还原功能。
